name: Build Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./interface_client
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build for macOS
        run: npm run package -- --mac

      - name: List contents of release folder
        run: ls -R release

      - name: Upload mac x64 build
        uses: actions/upload-artifact@v4
        with:
          name: mac-x64
          path: release/mac/**/*

      - name: Upload mac arm64 build
        uses: actions/upload-artifact@v4
        with:
          name: mac-arm64
          path: release/mac-arm64/**/*

      - name: Upload mac dmg
        uses: actions/upload-artifact@v4
        with:
          name: mac-dmg
          path: release/*.dmg

  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./interface_client
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build for Linux
        run: npm run package -- --linux

      - name: List contents of release folder
        run: ls -R release

      - name: Upload Linux AppImage
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimage
          path: release/*.AppImage

      - name: Upload other Linux builds
        uses: actions/upload-artifact@v4
        with:
          name: linux-extra
          path: release/linux-*/**

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./interface_client
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build for Windows
        run: npm run package -- --win

      - name: List contents of release folder
        run: dir release /s

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: release/*.exe

      - name: Upload other Windows builds
        uses: actions/upload-artifact@v4
        with:
          name: windows-extra
          path: release/win-*/**
