name: Build Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./interface_client
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build for macOS
        run: npm run package -- --mac

      - name: Upload mac x64
        uses: actions/upload-artifact@v4
        with:
          name: mac-x64
          path: |
            interface_client/release/mac/**
      
      - name: Upload mac arm64
        uses: actions/upload-artifact@v4
        with:
          name: mac-arm64
          path: |
            interface_client/release/mac-arm64/**

      - name: Upload dmg
        uses: actions/upload-artifact@v4
        with:
          name: mac-dmg
          path: |
            interface_client/release/*.dmg

  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./interface_client
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build for Linux
        run: npm run package -- --linux

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            interface_client/release/*.AppImage
            interface_client/release/linux-*/**

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./interface_client
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build for Windows
        run: npm run package -- --win

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            interface_client/release/*.exe
            interface_client/release/win-*/**

